// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJFSzl53KJGRox3Y7ExbvIG2oSGwOZnMo',
    appId: '1:317014636904:web:06dc13a1762c0c986bfedd',
    messagingSenderId: '317014636904',
    projectId: 'flutter-app-domicilios',
    authDomain: 'flutter-app-domicilios.firebaseapp.com',
    storageBucket: 'flutter-app-domicilios.appspot.com',
    measurementId: 'G-TZTCSSBTP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmYRPAaNQq0X7RzS19IsNCoWnh-8VttPE',
    appId: '1:317014636904:android:64543df2ec8ff9506bfedd',
    messagingSenderId: '317014636904',
    projectId: 'flutter-app-domicilios',
    storageBucket: 'flutter-app-domicilios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA06PMBA6pzneH8XjDFjRuhRBQvELTGZWw',
    appId: '1:317014636904:ios:7082aa100d08c8e06bfedd',
    messagingSenderId: '317014636904',
    projectId: 'flutter-app-domicilios',
    storageBucket: 'flutter-app-domicilios.appspot.com',
    iosClientId: '317014636904-rs4cl1m6livr1hi94o6cf6bhbuq4qvcm.apps.googleusercontent.com',
    iosBundleId: 'app.moviles.flutterDomiciliosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA06PMBA6pzneH8XjDFjRuhRBQvELTGZWw',
    appId: '1:317014636904:ios:7082aa100d08c8e06bfedd',
    messagingSenderId: '317014636904',
    projectId: 'flutter-app-domicilios',
    storageBucket: 'flutter-app-domicilios.appspot.com',
    iosClientId: '317014636904-rs4cl1m6livr1hi94o6cf6bhbuq4qvcm.apps.googleusercontent.com',
    iosBundleId: 'app.moviles.flutterDomiciliosApp',
  );
}
